<a href="https://colab.research.google.com/github/Ismailchan/Demand-Forecasting-and-Inventory-optimization/blob/main/Demand_and_inventory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
url = 'https://raw.githubusercontent.com/Ismailchan/Demand-Forecasting-and-Inventory-optimization/refs/heads/main/demand_inventory.csv'
df = pd.read_csv(url)
df.head()

   Unnamed: 0        Date Product_ID  Demand  Inventory
0           0  2023-06-01         P1      51       5500
1           1  2023-06-02         P1     141       5449
2           2  2023-06-03         P1     172       5308
3           3  2023-06-04         P1      91       5136
4           4  2023-06-05         P1     198       5045

In [4]:
df = df.drop(columns=['Unnamed: 0'])
df.head()

         Date Product_ID  Demand  Inventory
0  2023-06-01         P1      51       5500
1  2023-06-02         P1     141       5449
2  2023-06-03         P1     172       5308
3  2023-06-04         P1      91       5136
4  2023-06-05         P1     198       5045